title: Justin Johnson
subtitle: Information Systems Security Engineer
description: >- # this means to ignore newlines until "baseurl:"
  I am an enthusiastic Information Systems Security Engineer/Cybersecurity Engineer.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Justin Johnson
author_bio: Hi, my name is Justin Johnson. I'm a Lead Information Systems Security Engineer/Cybersecurity Engineer and a lifelong learner.
author_email: "justin@initcyber.com"
author_location: Atlanta, GA
author_website_url: "https://www.initcyber.com"
typewrite-text: devlopr is a jekyll framework built for developers. You can edit this in _config.yml file
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: SeKON
              company_logo: sekon.png
              company_url: https://www.sekon.com
              designation: Lead Information Systems Security Engineer
              description: I have responsibly led a team of Information System Security Engineers and received multiple recognitions from Government Leadership on outstanding performance. Responsible for Cyber Security Engineering, Vulnerability Management, Compliance Management, and following NIST Guidelines/Risk Management Framework. Also performed roles in Data-Analytics and Business Development.
              visibility: true
            - company_name: Georgia Tech Research Institute
              company_logo: gtri.png
              company_url: https://gtri.gatech.edu/
              designation: Information Systems Security Officer
              description: Responsible for ensuring information systems were properly maintained and security documentation was kept up to date in accordance with NIST 800-37 utilizing NIST 800-53 controls and the JSIG.
              visibility: true
            - company_name: Mount Vernon Towers
              company_logo: mvt.png
              company_url: https://mountvernontowers.com/
              designation: I.T. Technician
              description: I was a part of an Information Technology Team who assisted both residents and employees with IT Tasks. I managed both wireless and wired networks, infrastructure, and networks.
              visibility: true

# Education
author_education_details:
              - college_logo: csuglobal.jpg
                college_name: Colorado State University - Global Campus
                college_url: https://csuglobal.edu/
                college_degree: Cybersecurity/Information Technology
                description: Bachelor of Science
                visibility: true
              - college_logo: fsu.png 
                college_name: Florida State University
                college_url: https://fsu.edu
                college_degree: Criminology
                description: Bachelor of Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: github.jpg
                project_title: Homelab DevSecOps
                project_description: Homelab DevSecOp is a project I'm working on for Homelab automation of programs (CI/CD), and incorporating security tools for a mock "DevSecOp" environment.
                project_url: https://github.com/initcyber/homelab_devsecop
                visibility: true
              - project_thumbnail: apister.png
                project_title: APIster
                project_description: WIP - APIster is designed to scrape a given URL/IP-Address for any open (possibly undocumented) API's, and provide feedback on data obtained
                project_url: https://github.com/initcyber/APIster
                visibility: true

# social links
twitter_username: initcyberdotcom
github_username:  initcyber
facebook_username: johndoe
linkedin_username: johndoe
behance_username: johndoe
instagram_username: johndoe
medium_username: johndoe
telegram_username: johndoe
dribbble_username: johndoe
flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
